apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-secretd.fullname" . }}-config
  labels:
    {{- include "agent-secretd.labels" . | nindent 4 }}
data:
  config.yaml: |
    services:
      {{- .Values.serviceRegistry | toYaml | nindent 6 }}
